# Generated by Django 5.2.4 on 2025-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
