# Generated by Django 5.2.2 on 2025-07-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_userlocation_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(upload_to='kyc/pan/')),
                ('aadhar_passport_dl', models.FileField(upload_to='kyc/id/')),
                ('gst_certificate', models.FileField(upload_to='business/gst/')),
                ('business_registration_cert', models.FileField(upload_to='business/registration/')),
                ('shop_license', models.FileField(blank=True, null=True, upload_to='business/shop_license/')),
                ('cancelled_cheque', models.FileField(upload_to='bank/cheque/')),
                ('bank_statement', models.FileField(upload_to='bank/statement/')),
                ('it_return', models.FileField(blank=True, null=True, upload_to='finance/it_return/')),
                ('financial_statement', models.FileField(blank=True, null=True, upload_to='finance/statement/')),
                ('dealership_letter', models.FileField(blank=True, null=True, upload_to='supporting/dealership/')),
                ('authorized_signatory_letter', models.FileField(blank=True, null=True, upload_to='supporting/signatory/')),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.FileField(upload_to='agreements/form/')),
                ('nda_agreement', models.FileField(upload_to='agreements/nda/')),
                ('terms_conditions', models.FileField(upload_to='agreements/terms/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendorprofile')),
            ],
        ),
    ]
