# Generated by Django 5.2.2 on 2025-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_staff',
            field=models.BooleanField(default=False),
        ),
    ]
