# Generated by Django 5.2.4 on 2025-09-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
