# Generated by Django 5.2.4 on 2025-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendorprofile_razorpay_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
