# Generated by Django 5.2.4 on 2025-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
