# Generated by Django 5.2.2 on 2025-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendorprofile_vendoragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='aadhar_passport_dl',
            field=models.FileField(blank=True, null=True, upload_to='kyc/id/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='bank/statement/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_registration_cert',
            field=models.FileField(blank=True, null=True, upload_to='business/registration/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='cancelled_cheque',
            field=models.FileField(blank=True, null=True, upload_to='bank/cheque/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='business/gst/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
    ]
