# Generated by Django 5.2.2 on 2025-07-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_userdevice_userlocation'),
        ('accounts', '0004_vendorprofile_company_name_and_more'),
    ]

    operations = [
    ]
