# Generated by Django 5.2.2 on 2025-07-26 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendorprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='kyc_name',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='designation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='signed_terms_and_con',
            field=models.FileField(blank=True, null=True, upload_to='supporting/termsandcondition/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='type_of_vendor',
            field=models.CharField(choices=[('business', 'business')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_registration_form',
            field=models.FileField(blank=True, null=True, upload_to='supporting/regform/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
