# Generated by Django 5.2.4 on 2025-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendorprofile_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
