# Generated by Django 5.2.4 on 2025-08-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0002_remove_variant_model_remove_variantyear_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_varient_year',
            field=models.ManyToManyField(blank=True, related_name='compatible_products', to='vehicles.vehiclevariant'),
        ),
    ]
