# Generated by Django 5.2.2 on 2025-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_varient_year',
            field=models.ManyToManyField(blank=True, related_name='compatible_products', to='vehicles.variantyear'),
        ),
    ]
