# Generated by Django 5.2.4 on 2025-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='breadth',
            field=models.IntegerField(default=10, help_text='Breadth in CM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=10, help_text='Height in CM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(default=10, help_text='Length in CM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=256),
        ),
    ]
