# Generated by Django 5.2.4 on 2025-08-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_compatible_varient_year'),
        ('products', '0003_remove_product_tags_product_tag'),
    ]

    operations = [
    ]
