# Generated by Django 5.2.2 on 2025-06-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_productimage_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
