# Generated by Django 6.0.6 on 2026-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
