# Generated by Django 5.2.4 on 2025-08-06 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='model',
        ),
        migrations.RemoveField(
            model_name='variantyear',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variantyear',
            name='year',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='image',
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehiclemake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehiclemodel')),
            ],
            options={
                'unique_together': {('make', 'model', 'variant', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedvehicle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedvehicle',
            name='vehicle_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='vehicles.vehiclevariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='savedvehicle',
            unique_together={('user', 'vehicle_variant')},
        ),
        migrations.DeleteModel(
            name='ModelYear',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.RemoveField(
            model_name='savedvehicle',
            name='vehicle_variant_year',
        ),
        migrations.DeleteModel(
            name='VariantYear',
        ),
    ]
