# Generated by Django 5.2.4 on 2025-08-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclevariant',
            name='variant',
            field=models.CharField(choices=[('PETROL', 'petrol'), ('DIESEL', 'diesel'), ('CNG', 'cng'), ('ELECTRIC', 'electric')], max_length=20),
        ),
    ]
