# Generated by Django 5.2.4 on 2025-08-01 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'PERCENTAGE'), ('FIXED', 'fixed'), ('BOGO', 'buy one get one')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount Value', max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('activate', models.BooleanField(default=True)),
                ('applicable_product', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
        ),
    ]
