# Generated by Django 5.2.4 on 2025-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applicable_category',
            field=models.ManyToManyField(blank=True, related_name='category', to='products.category'),
        ),
    ]
