# Generated by Django 6.0.6 on 2026-07-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0001_initial'),
        ('products', '0004_remove_productvariant_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category'),
        ),
    ]
