# Generated by Django 6.0.6 on 2026-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0002_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
