# Generated by Django 5.2.4 on 2025-08-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0002_coupon'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='coupon', to='products.product'),
        ),
    ]
