# Generated by Django 5.2.4 on 2025-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0002_promotion_applicable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='price_range',
            field=models.DecimalField(decimal_places=2, help_text='price range', max_digits=10, null=True),
        ),
    ]
