# Generated by Django 5.2.4 on 2025-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_promotion', '0003_promotion_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
