# Generated by Django 5.2.4 on 2025-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
