# Generated by Django 5.2.4 on 2025-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
