# Generated by Django 5.2.2 on 2025-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_cost_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('phonepe', 'PhonePe'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
    ]
