# Generated by Django 5.2.4 on 2025-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
