# Generated by Django 6.0.6 on 2026-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
