# Generated by Django 5.2 on 2026-08-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_courier_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_request', 'Return Requested'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Customer-provided reason for return')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('return_shiprocket_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('return_shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('return_awb_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shiprocket_shipping_charge', models.DecimalField(decimal_places=2, default=0, help_text='Reverse pickup charge billed by Shiprocket (deducted from refund)', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual refund issued = order item total - shiprocket_shipping_charge', max_digits=10)),
                ('refund_id', models.CharField(blank=True, help_text='Razorpay/Stripe refund transaction ID', max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
